version: "3.4"

services:

  nginx:
    container_name: reservation-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "4010:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    container_name: reservation-php-fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        IS_DEV: 1
    volumes:
      - .:/var/www/html
      - ~/.ssh:/root/.ssh:ro
    environment:
      - XDEBUG_MODE=off
      - PHP_IDE_CONFIG=serverName=reserving-php-fpm

  mysql:
    container_name: reservation-mysql
    image: mysql:latest
    ports:
      - 3397:3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass' # TODO: Change this
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
