controllers:
    resource: ../src/Controller/
    type: attribute
login:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::login
sign_up:
    path: /sign_up
    methods: POST
    controller: App\Controller\LoginController::signUp
sign_in:
    path: /sign_in
    methods: POST
    controller: App\Controller\LoginController::signIn
logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout
