controllers:
    resource: ../src/Controller/
    type: attribute

login:
    path: /login
    methods: [POST, GET]
    controller: App\Controller\LoginController::login

sign_up:
    path: /sign_up
    methods: [POST, GET]
    controller: App\Controller\SignUpController::signUp

booking:
    path: /booking
    methods: [POST, GET]
    controller: App\Controller\BookingController::booking

logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout

home:
    path: /
    methods: [GET, POST]
    controller: App\Controller\HomeController::home

rooms:
    path: /rooms
    methods: [GET, POST]
    controller: App\Controller\RoomController::room

deskReservation:
    path: /deskReservation
    methods: [GET, POST]
    controller: App\Controller\DeskReservationController::deskReservation

allReservations:
    path: /allReservations
    methods: [GET, POST]
    controller: App\Controller\AllReservationsController::allReservations

deleteReservations:
    path: /deleteReservations
    methods: [GET, POST]
    controller: App\Controller\AllReservationsController::deleteReservations

sign_in:
    path: /signIn
    methods: [ POST, GET ]
    controller: App\Controller\SignInController::signIn

forgotPassword:
    path: /forgotPassword
    methods: [ POST, GET ]
    controller: App\Controller\LoginController::forgotPassword

sendForgotPassword:
    path: /sendForgotPassword
    methods: POST
    controller: App\Controller\LoginController::sendForgotPassword

resetPage:
    path: /resetPage
    methods: GET
    controller: App\Controller\LoginController::resetPage

reset_type_new_password:
    path: /reset_type_new_password
    methods: POST
    controller: App\Controller\LoginController::resetTypeNewPassword