controllers:
    resource: ../src/Controller/
    type: attribute
login:
    path: /login
    methods: [POST, GET]
    controller: App\Controller\LoginController::login
sign_up:
    path: /sign_up
    methods: [POST, GET]
    controller: App\Controller\SignUpController::signUp
booking:
    path: /booking
    methods: [POST, GET]
    controller: App\Controller\BookingController::booking
logout:
    path: /logout
    methods: GET
    controller: App\Controller\LoginController::logout
home:
    path: /
    methods: [GET, POST]
    controller: App\Controller\HomeController::home

#picked_date:
#    path: /picked_date
#    methods: POST
#    controller: App\Controller\BookingController::pikedDate
