controllers:
    resource: ../src/Controller/
    type: attribute
login:
    path: /login
    methods: GET
    controller: App\Controller\LoginController::login
sign_up:
    path: /sign_up
    methods: POST
    controller: App\Controller\SignUpController::signUp
